package koporscho;
import graphic.IViewable;
import graphic.View;
import proto.Prototype;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.StringJoiner;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Koporscho csapat Projlab 
//  @ File Name : Virologist.java
//  @ Date : 2022. 03. 25.
//  @ Authors : Szab� Egon, Bir� Ferenc, T�th B�lint, Ferge M�t�, Rahmi D�niel
//
//


/** A Virológust reprezentálja a játéban*/
public class Virologist extends Character implements IViewable {
	private int apMax, apCurrent;

	/** Tárolja a jelenlegi és a maximum anyagokat*/
	private Materials materials, maxMaterials;
	
	/** Tárolja a felszereléseket, amelyek a virológusnál van*/
	private ArrayList<Equipment> equipment;
	
	/** Tárolja az elkészített ágenseket, amelyek a virológusnál van*/
	private ArrayList<Agent> agentInventory;
	
	/** Tárolja a recepteket, melyeket megtanult a virológus*/
	private ArrayList<Agent> agentRecipes;

	/** Virológus neve*/
	private final String name;

	private ArrayList<View> views=new ArrayList<>();

	/** A Virológus konstruktora.*/
	public Virologist(String n){
		name=n;
		equipment = new ArrayList<>();
		agentInventory = new ArrayList<>();
		agentRecipes = new ArrayList<>();
		apMax=3;
		apCurrent=3;
	}

	/**
	 * A Character osztály Move függvényének fölüldefiniálása
	 * @param field Célmező, amelyre a charactert mozgatjuk.
	 */
	@Override
	public void Move(Field field){
		if(currentField!=null)
			apCurrent--;
		super.Move(field);
		NotifyViews();
	}

	/**
	 * Elkészíti a paraméterként beadott ágenst
	 * @param agent Az ágens amit készít a virológus
	 * */
	public void CraftAgent(Agent agent) {
		apCurrent--;
		if (agentRecipes.contains(agent) && materials.CanCraft(agent.GetRecipe())) {
			agentInventory.add(agent);
			materials.SetNucleotide(materials.GetNucleotide() - agent.GetRecipe().GetNucleotide());
			materials.SetAminoAcid(materials.GetAminoAcid() - agent.GetRecipe().GetNucleotide());
		}
		NotifyViews();
	}
	
	/**
	 *A virológus eszköztárához hozzáadja a paraméterként kapott anyagokat.
	 * @param m Hozzáadandó anyagok
	 * */
	public void AddMaterials(Materials m) {
		materials.SetNucleotide(materials.GetNucleotide() + m.GetNucleotide());
		materials.SetAminoAcid(materials.GetAminoAcid() + m.GetNucleotide());
		NotifyViews();
	}

	/**
	 * A virológus eszköztárához hozzáadja a paraméterként kapott ágenst.
	 * @param agent Hozzáadandó ágens
	 */
	public void AddAgent(Agent agent) {
		agentInventory.add(agent);
		NotifyViews();
	}

	/**
	 * A virológus megtanulja egy ágens receptjét, genetikai kódját.
	 * @param agent Megtanulandó ágens
	 */
	public void LearnRecipe(Agent agent) {
		if(!agentRecipes.contains(agent))
			agentRecipes.add(agent);
		NotifyViews();
	}

	/** A virológus elfelejti egy ágens receptjét. */
	public void ForgetRecipes() {
		agentRecipes.clear();
		NotifyViews();
	}

	/**
	 *A virológus felkeni a paraméterként kapott ágenst a paraméterként kapott célpontra
	 * @param target Célpont
	 * @param agent Ágens
	 */
	public void ApplyAgent(Character target, Agent agent) {
		target.HandleAgent(this, agent, false);
		this.RemoveAgent(agent);
		apCurrent--;
		NotifyViews();
	}

	/**
	 * A virológus ellop egy felszerelést a paraméterként kapott karaktertől.
	 * @param target Célpont, akitől a virológus lop
	 * @param e Tárgy, amit a virológus ellop
	 */
	public void StealEquipment(Character target, Equipment e) {
		boolean success = ((Virologist)target).HandleSteal(this, e);

		if(success){
			this.AddEquipment(e);
			apCurrent--;
		}
		NotifyViews();
	}

	/**
	 * Eltávolítja a paraméterként kapott ágenst a virológustól.
	 * @param a Eltávolítandó ágens
	 */
	public void RemoveAgent(Agent a) {
		agentInventory.remove(a);
	}
	
	/** A mezőn végezhető művelet meghívása.*/
	public void Interact() {
		apCurrent--;
		VirologistVisitor Vis = new VirologistVisitor(this);
		currentField.React(Vis);
		NotifyViews();
	}

	/**
	 * A virológus felvesz egy felszerelést az eszköztárába.
	 * @param e Felszerelés, amit a virológus felvesz
	 */
	public void AddEquipment(Equipment e) {
		equipment.add(e);
		StatusEffect ef = e.GetEffect();
		if(!ef.GetDead())
			activeEffects.add(e.GetEffect());
		NotifyViews();
	}

	/**
	 * A virológus megtámad a baltával egy másik virológust
	 * @param target A célpont virológus
	 */
	public void Chop(Virologist target)
	{
		for(Equipment e : this.GetEquipment())
		{
			if(e.GetEffect().GetDead() && e.GetDurability() > 0)
			{
				target.AddEffect(e.GetEffect());
				e.DecreaseDurability();
				apCurrent--;
			}
		}
		NotifyViews();
	}

	/**
	 *  A virológus eltávolít egy felszerelést az eszköztárából.
	 * @param e Eltávolítandó felszerelés
	 */
	public void RemoveEquipment(Equipment e) {
		equipment.remove(e);
		activeEffects.remove(e.GetEffect());
		NotifyViews();
	}

	/**
	 * Kezeli a lopást.
	 * @param source A lopást elkövető virológus
	 * @param e Ellopott felszerlés
	 * @return igazzal tér vissza, ha sikeres volt.
	 */
	public boolean HandleSteal(Virologist source, Equipment e) {
		boolean paralyzed = false;
		for(StatusEffect ef:activeEffects) {
			if(ef.GetParalyzed()) {
				paralyzed = true;
				break;
			}
		}
		if(paralyzed) {
			this.RemoveEquipment(e);
		}
		NotifyViews();
		return paralyzed;
	}

	/**
	 * Implicit getter a virológus által ismert ágens-receptek lekérdezésére.
	 * @return A virológus által ismert ágens-receptek.
	 */
	public ArrayList<Agent> GetRecipes() {
		return agentRecipes;
	}

	/**
	 * Implicit getter a virológus által ismert ágens-inventory lekérdezésére.
	 * @return Ismert ágensek
	 */
	public ArrayList<Agent> GetAgentInventory() {
		return agentInventory;
	}

	/**
	 * Implicit getter a virológus által birtokolt anyagok lekérdezésére.
	 * @return A virológus által birtokolt anyagok
	 */
	public Materials GetCurrentMaterials() {
		return materials;
	}

	/**
	 * Implicit getter a virológus által birtokolható maximális anyagok lekérdezésére.
	 * @return A virológus által birtokolható maximális anyagok
	 */
	public Materials GetMaxMaterials() {
		return maxMaterials;
	}

	/**
	 * Implicit getter a virológus által birtokolt felszerelések lekérdezésére.
	 * @return
	 */
	public ArrayList<Equipment> GetEquipment(){
		return equipment;
	}


	/** Az idő múlását szimuláló függvény */
	@Override
	public void Tick() {
		//check for bear
		boolean isBear = false;
		boolean isParalyzed = false;
		for (StatusEffect e : activeEffects) {
			if (e.GetBear()) {
				isBear = true;
			}
			else if(e.GetParalyzed()){
				isParalyzed = true;
			}
		}

		if(isBear && !isParalyzed)
		{
			StatusEffect.Bear(this);
			((Virologist)this).SetApCurrent(0);
		}

		for (StatusEffect e : activeEffects) {
			if (e.GetAmnesia()) {
				ForgetRecipes();
				break;
			}
		}
		agentInventory.removeIf(a -> a.ReduceLifespan() == 0);
		super.Tick();
		NotifyViews();
	}

	/**
	 * Visszatér a karakter által ismert ágensek számával. A győztes kihirdetésénél használt függvény.
	 * @return karakter által ismert ágensek száma
	 */
	public int GetRecipeCount() {
		return agentRecipes.size();
	}

	public void SetMaxMaterials(Materials m)
	{
		maxMaterials = new Materials(m);
		NotifyViews();
	}

	public void SetMaterials(Materials m)
	{
		materials = new Materials(m);
		NotifyViews();
	}

	public String GetName() {
		return name;
	}

	public int GetApCurrent(){
		return apCurrent;
	}

	public void SetApCurrent(int val){
		apCurrent=val;
		NotifyViews();
	}

	public void RefreshAP() {
		apCurrent = apMax;
		NotifyViews();
	}

	/**
	 * Az Virologist osztály logger fügvénye, mely az adott virológus tulajdonságait írja ki a standard kimentre és fájlba.
	 * @throws java.io.IOException
	 */
	public void log() throws java.io.IOException{
		System.out.println(Prototype.objectIDs.get(this)+":");
		System.out.println("\tcurrentField: " + Prototype.objectIDs.get(currentField));
		System.out.println("\tapMax: "+ apMax);
		System.out.println("\tapCurrent: "+ apCurrent);

		System.out.print("\tagentRecipes: ");
		StringJoiner str = new StringJoiner(", ");
		for(Agent a: agentRecipes)
			str.add(Prototype.objectIDs.get(a));
		System.out.println(str.length()==0?"-":str);

		System.out.print("\tagentInventory: ");
		str = new StringJoiner(", ");
		for(Agent a: agentInventory)
			str.add(Prototype.objectIDs.get(a));
		System.out.println(str.length()==0?"-":str);

		System.out.print("\tmaterials: ");
		if(materials!=null) {
			System.out.println("\n\t\tnucleotide: " + materials.GetNucleotide());
			System.out.println("\t\taminoacid: " + materials.GetAminoAcid());
		}
		else
			System.out.println("-");
		System.out.print("\tmaxMaterials: ");
		if(maxMaterials!=null) {
			System.out.println("\n\t\tnucleotide: " + maxMaterials.GetNucleotide());
			System.out.println("\t\taminoacid: " + maxMaterials.GetAminoAcid());
		}
		else
			System.out.println("-");
		System.out.print("\tequipment: ");
		str = new StringJoiner(", ");
		for(Equipment e: equipment)
			str.add(Prototype.objectIDs.get(e));
		System.out.println(str.length()==0?"-":str);

		System.out.print("\tactiveEffects: ");
		str = new StringJoiner(", ");
		for(StatusEffect s: activeEffects)
			str.add(Prototype.objectIDs.get(s));
		System.out.println(str.length()==0?"-":str);

		/////////////////

		Prototype.writer.write(Prototype.objectIDs.get(this)+":"+"\n");
		Prototype.writer.write("\tcurrentField: " + Prototype.objectIDs.get(currentField)+"\n");
		Prototype.writer.write("\tapMax: "+ apMax+"\n");
		Prototype.writer.write("\tapCurrent: "+ apCurrent+"\n");

		Prototype.writer.write("\tagentRecipes: ");
	    str = new StringJoiner(", ");
		for(Agent a: agentRecipes)
			str.add(Prototype.objectIDs.get(a));
		Prototype.writer.write((str.length()==0?"-":str.toString())+"\n");

		Prototype.writer.write("\tagentInventory: ");
		str = new StringJoiner(", ");
		for(Agent a: agentInventory)
			str.add(Prototype.objectIDs.get(a));
		Prototype.writer.write((str.length()==0?"-":str.toString())+"\n");

		Prototype.writer.write("\tmaterials: ");
		if(materials!=null) {
			Prototype.writer.write("\n\t\tnucleotide: " + materials.GetNucleotide()+"\n");
			Prototype.writer.write("\t\taminoacid: " + materials.GetAminoAcid()+"\n");
		}
		else
			Prototype.writer.write("-"+"\n");
		Prototype.writer.write("\tmaxMaterials: ");
		if(maxMaterials!=null) {
			Prototype.writer.write("\n\t\tnucleotide: " + maxMaterials.GetNucleotide()+"\n");
			Prototype.writer.write("\t\taminoacid: " + maxMaterials.GetAminoAcid()+"\n");
		}
		else
			Prototype.writer.write("-"+"\n");
		Prototype.writer.write("\tequipment: ");
		str = new StringJoiner(", ");
		for(Equipment e: equipment)
			str.add(Prototype.objectIDs.get(e));
		Prototype.writer.write((str.length()==0?"-":str.toString())+"\n");

		Prototype.writer.write("\tactiveEffects: ");
		str = new StringJoiner(", ");
		for(StatusEffect s: activeEffects)
			str.add(Prototype.objectIDs.get(s));
		Prototype.writer.write((str.length()==0?"-":str.toString())+"\n");
	}

	public void NotifyViews() {
		for(View v: views){
			v.Redraw(this);
		}
	}

	public void AddView(View view) {
		views.add(view);
	}

	public void RemoveView(View view) {
		views.remove(view);
	}
}
